// Generated by CoffeeScript 1.9.3
(function() {
  var _, assert, haha, help, should, util, youmin;

  assert = require("assert");

  should = require('chai').should();

  _ = require("lodash");

  util = require("./public/util");

  help = require("./spider/core/spiderHelper");

  haha = require("./spider/haha/haha");

  youmin = require("./spider/youmin/youmin");

  describe("core", function() {
    it("#getUrlThen", function(done) {
      var url;
      url = "www.baidu.com";
      return help.getUrlThen(url).then(function(cont, data) {
        data.should.a("string").and.ok;
        data.length.should.above(100);
        return done();
      });
    });
    return it("#log is define", function() {
      return help.log.should.a("function").and.ok;
    });
  });

  (function(model) {
    return model.should.ok.and.should.property("Title").and.should.property("Context");
  });

  describe("haha spider config ", function() {
    it("#getModelThen()", function(done) {
      return haha.getModelThen(haha.exurl).then(function(cont, model, zb) {
        model.Content.length.should.above(1);
        zb.zan.should.ok;
        zb.bishi.should.ok;
        return done();
      });
    });
    return it("#getCurrentThen()", function(done) {
      return haha.getCurrentThen().then(function(cont, urls) {
        urls.should.be.a("array");
        urls.length.should.equal(16);
        _.all(urls, function(url) {
          url.should.be.a("string");
          return url.length > 1;
        }).should.ok;
        return done();
      });
    });
  });

  describe(" youmin spidr config ", function() {
    it("#getModelThen()", function(done) {
      return youmin.getModelThen("").then(function(cont, model, zb) {
        return done();
      });
    });
    return it("#getCurrentThen()", function(done) {
      return haha.getCurrentThen().then(function(cont, urls) {
        urls.should.be.a("array");
        urls.length.should.equal(16);
        _.all(urls, function(url) {
          url.should.be.a("string");
          return url.length > 1;
        }).should.ok;
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=spider.js.map
