// Generated by CoffeeScript 1.9.3
(function() {
  var _, o, taskFactory;

  _ = require('lodash');

  taskFactory = {
    tasks: []
  };

  o = taskFactory;

  o.getAllNames = function() {
    return _.map(o.tasks, function(item) {
      return item.name;
    });
  };

  o.getAll = function() {
    return o.tasks;
  };

  o.add = function(item) {
    var names;
    names = o.getAllNames();
    if (!_.includes(names, item.name)) {
      return o.tasks.push(item);
    }
  };

  o.get = function(name) {
    return _.find(o.tasks, function(item) {
      return item.name === name;
    });
  };

  o.start = function(name) {
    var item;
    item = o.get(name);
    if (item) {
      return item.start();
    }
  };

  o.stop = function(name) {
    var item;
    item = o.get(name);
    if (item) {
      return item.stop();
    }
  };

  module.exports = o;

}).call(this);

//# sourceMappingURL=taskFactory.js.map
