// Generated by CoffeeScript 1.9.3
(function() {
  var Hour, Min, TaskItem, _, defOpt;

  _ = require('lodash');

  Min = 60 * 1000;

  Hour = 60 * Min;

  defOpt = {
    interval: 30 * Min
  };

  TaskItem = function(name, trigger, opt) {
    var me;
    me = this;
    me.status = 0;
    me.option = _.assign(defOpt, opt);
    me.task = {};
    me.name = name;
    if (_.isFunction(trigger)) {
      me.trigger = trigger;
    } else {
      throw new error("callFun is not allow empty");
    }
    return me;
  };

  TaskItem.prototype.start = function() {
    var me;
    me = this;
    me.status = 1;
    this.task = setInterval(me.trigger, me.option.interval);
    return me.trigger();
  };

  TaskItem.prototype.stop = function() {
    var me;
    me = this;
    me.status = 2;
    return clearInterval(me.task);
  };

  module.exports = TaskItem;

}).call(this);

//# sourceMappingURL=TaskItem.js.map
